formatter: markdown

sections:
  hide: []
  show: [providers, requirements, inputs, outputs]

content: |-
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Example
  ```terraform
  {{ include "examples/default.tf" }}
  ```

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->